name: ci-release-operator

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag which has to be updated"
        type: "string"
        required: true
      trivy_scan:
        description: 'Enable trivy scan'
        required: true
        type: boolean    
  push:
    branches:
      - "main"
      - "v*"
    paths:
      # release on any dependency change
      - "pkg/**"
      - "deployments/get/**"
      - "KubeArmor/utils/**"
  create:
    branches:
      - "v*"

# Declare default permissions as read only.
permissions: read-all

env:
  PLATFORM: linux/amd64,linux/arm64/v8

jobs:
  kubearmor-operator-release:
    name: Build & Push KubeArmor Operator
    if: github.repository == 'kubearmor/kubearmor'        
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}
      
      - name: Get Tag
        id: vars
        uses: actions/github-script@v7
        with:
          script: |
            let tag;
            if (context.eventName === 'workflow_dispatch') {
              tag = context.payload.inputs.tag;
              core.info(`Checking out tag: ${tag}`);
              await exec.exec('git', ['checkout', tag]);
            } else {
              const ref = context.ref;
              tag = ref === "refs/heads/main" ? "latest" : ref.replace(/^refs\/[^/]+\//, "");
            }
            core.setOutput('tag', tag);
            console.log(`Creating operator release with tag: ${tag}`);

      - name: Build & Save KubeArmor Operator
        if: ${{ github.event.inputs.trivy_scan}}
        working-directory: ./pkg/KubeArmorOperator
        run: PLATFORM=linux/amd64 make docker-buildx TAG=${{ steps.vars.outputs.tag }} BUILD_MODE=--load

      - name: Save KubeArmorOperator image to tar for Trivy Scan
        if: ${{ github.event.inputs.trivy_scan}}
        run: |
          docker save -o kubearmor-operator.tar kubearmor/kubearmor-operator:${{ steps.tag.outputs.tag }}
          docker save -o kubearmor-snitch.tar kubearmor/kubearmor-snitch:${{ steps.tag.outputs.tag }}

      - name: Build & Push KubeArmor Operator
        working-directory: ./pkg/KubeArmorOperator
        run: PLATFORM=$PLATFORM make docker-buildx TAG=${{ steps.vars.outputs.tag }} BUILD_MODE=--push

      - name: Run Trivy vulnerability scanner KubeArmorController
        if: ${{ github.event.inputs.trivy_scan}}
        id: scan_init
        uses: aquasecurity/trivy-action@0.28.0
        with:
          input: ./pkg/KubeArmorOperator/kubearmor-operator.tar
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 
        continue-on-error: true   

      - name: Run Trivy vulnerability scanner kubearmor-ubi
        if: ${{ github.event.inputs.trivy_scan}}
        id: scan_ubi
        uses: aquasecurity/trivy-action@0.28.0
        with:
          input: ./pkg/KubeArmorOperator/kubearmor-snitch.tar
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'  
        continue-on-error: true    

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Get Image Digest
        id: digest
        run: |
          echo "operatordigest=$(jq -r '.["containerimage.digest"]' kubearmor-operator.json)" >> $GITHUB_OUTPUT
          echo "snitchdigest=$(jq -r '.["containerimage.digest"]' kubearmor-snitch.json)" >> $GITHUB_OUTPUT

      - name: Sign the Container Images
        run: |
          cosign sign -r kubearmor/kubearmor-operator@${{ steps.digest.outputs.operatordigest }} --yes
          cosign sign -r kubearmor/kubearmor-snitch@${{ steps.digest.outputs.snitchdigest }} --yes

      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Get and Match Stable Tag
        id: stable
        run: |
          value=`cat STABLE-RELEASE`
          if [ ${{ github.ref }} == "refs/heads/$value" ]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi

      - name: Install regctl
        if: steps.stable.outputs.match == 'true'
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
          chmod 755 regctl
          mv regctl /usr/local/bin
  
      - name: Check install
        if: steps.stable.outputs.match == 'true'
        run: regctl version
      
      - name: Generate the stable version of Operator and Snitch in Docker Hub
        if: steps.stable.outputs.match == 'true'
        run: |
          STABLE_VERSION=`cat STABLE-RELEASE`
          regctl image copy kubearmor/kubearmor-operator:$STABLE_VERSION kubearmor/kubearmor-operator:stable --digest-tags
          regctl image copy kubearmor/kubearmor-snitch:$STABLE_VERSION kubearmor/kubearmor-snitch:stable --digest-tags
